# ---------------------------------------------------------------
format = """
[â–‘â–’â–“](#2e3440)\
$os\
$username\
[î‚°](bg:#3b4252 fg:#2e3440)\
$directory\
[î‚°](fg:#3b4252 bg:#434c5e)\
$git_branch\
$git_status\
$git_state\
[î‚°](fg:#434c5e bg:#4c566a)\
$terraform\
$c\
$python\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[î‚°](fg:#4c566a bg:#5e81ac)\
$docker_context\
[î‚°](fg:#5e81ac bg:#6272a4)\
$time\
[î‚° ](fg:#6272a4)\
\n
$cmd_duration\
$character\
"""
#add_newline = false

[line_break]
disabled = false

[username]
show_always = true
style_user = "bg:#2e3440"
style_root = "bg:#9A348E"
format = '[ó°€µ $user ]($style)'
disabled = false

[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "bg:#3b4252"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[c]
symbol = "î˜ "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "î˜† "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#5e81ac"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = "î‰µ "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "ï˜"
style = "bg:#434c5e"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#434c5e"
format = '[$all_status$ahead_behind ]($style)'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[golang]
symbol = "î˜§ "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ïš¤ "
style = "bg:##434c5e"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "îœ· "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#6272a4"
format = '[ ïº $time ]($style)'
	
[character]
success_symbol = '[ âœ](#6272a4)'
error_symbol = '[ âœ](bold red)'
#style = "bg:#6272a4"

[cmd_duration]
min_time = 500
format = ' [$duration](#6272a4)'
